name: bullet
description: Bullet provides a quick, straightforward, and comprehensive list of activities that students may access online.
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_analytics: ^10.1.4
  firebase_core: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true