name: bullet
description: Bullet provides a quick, straightforward, and comprehensive list of activities that students may access online.
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  firebase_analytics: ^10.4.1
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  firebase_database: ^10.2.1
  flutter_datetime_picker: ^1.5.1
  multi_select_flutter:
    path: "./multi_select_flutter-4.1.3/"
  emoji_picker_flutter: ^1.5.4
  google_fonts: ^4.0.4
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.2.0
  flutter_profile_picture: ^2.0.0
  flutter_native_splash: ^2.2.19
  image_picker: ^0.8.7+5
  firebase_storage: ^11.2.1
  universal_io: ^2.2.0
  google_sign_in: ^6.1.2
  intl: ^0.18.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  build_web_compilers: ^3.2.7

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/onboarding/
    - lib/assets/images/services/
    - lib/assets/images/

  fonts:
    - family: SF-Pro
      fonts:
        - asset: lib/assets/fonts/sf-pro/SF-Pro-Display-Black.otf
          weight: 900
        - asset: lib/assets/fonts/sf-pro/SF-Pro-Display-Heavy.otf
          weight: 800
        - asset: lib/assets/fonts/sf-pro/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: lib/assets/fonts/sf-pro/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: lib/assets/fonts/sf-pro/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: lib/assets/fonts/sf-pro/SF-Pro-Display-Regular.otf
        - asset: lib/assets/fonts/sf-pro/SF-Pro-Text-Light.otf
          weight: 300
        - asset: lib/assets/fonts/sf-pro/SF-Pro-Display-Thin.otf
          weight: 200
        - asset: lib/assets/fonts/sf-pro/SF-Pro-Display-Ultralight.otf
          weight: 100

    - family: Spotnik
      fonts:
        - asset: lib/assets/fonts/spotnik/Fontspring-DEMO-caspotnik-regular.otf
        - asset: lib/assets/fonts/spotnik/Fontspring-DEMO-caspotnik-bold.otf
          weight: 700
        - asset: lib/assets/fonts/spotnik/Fontspring-DEMO-caspotnik-italic.otf
          style: italic

flutter_native_splash:
  color: "#5C70F2"
  image: lib/assets/images/mascot_echo_writing.png
  android_12:
    color: "#5C70F2"
    image: lib/assets/images/mascot_echo_writing.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/images/mascot_echo_writing_square.png"
  min_sdk_android: 21