// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo70AY4uXarRSyrE0t0hHLhDaekjpUirs',
    appId: '1:931594052343:web:97245ed2d008c2843129f2',
    messagingSenderId: '931594052343',
    projectId: 'bullet-upvisayas',
    authDomain: 'bullet-upvisayas.firebaseapp.com',
    databaseURL: 'https://bullet-upvisayas-default-rtdb.firebaseio.com',
    storageBucket: 'bullet-upvisayas.appspot.com',
    measurementId: 'G-M9GSM500KR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1DxBBMY4bqJ96cZr5y8J67bc15B4wU7E',
    appId: '1:931594052343:android:20c346a1494df57f3129f2',
    messagingSenderId: '931594052343',
    projectId: 'bullet-upvisayas',
    databaseURL: 'https://bullet-upvisayas-default-rtdb.firebaseio.com',
    storageBucket: 'bullet-upvisayas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbyVfyBY6clBhl8Of0yoHqpjz1UAju1l4',
    appId: '1:931594052343:ios:7c660f9fc57f0a853129f2',
    messagingSenderId: '931594052343',
    projectId: 'bullet-upvisayas',
    databaseURL: 'https://bullet-upvisayas-default-rtdb.firebaseio.com',
    storageBucket: 'bullet-upvisayas.appspot.com',
    iosClientId: '931594052343-m53fon53dlhdh6klf2439ddokbeb92ts.apps.googleusercontent.com',
    iosBundleId: 'com.upvisayas.bullet.bullet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbyVfyBY6clBhl8Of0yoHqpjz1UAju1l4',
    appId: '1:931594052343:ios:7c660f9fc57f0a853129f2',
    messagingSenderId: '931594052343',
    projectId: 'bullet-upvisayas',
    databaseURL: 'https://bullet-upvisayas-default-rtdb.firebaseio.com',
    storageBucket: 'bullet-upvisayas.appspot.com',
    iosClientId: '931594052343-m53fon53dlhdh6klf2439ddokbeb92ts.apps.googleusercontent.com',
    iosBundleId: 'com.upvisayas.bullet.bullet',
  );
}
